name: Deploy Pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Slides
        run: |
          npm ci
          npm run build -- -o ../dist/slides --base /intro-to-elm-architecture/slides 
        working-directory: ./slides
      - name: Build Chuck Norris App
        run: |
          npm ci
          npm run lint 
          npm test
          npm run build:prod
          mkdir -p ../dist/chuck-norris-app
          cp -rv index.html main.js assets/ ../dist/chuck-norris
        working-directory: ./chuck-norris
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
